# Site settings
title: Brian Swisher
email: bswisher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  More than 17 years industry experience, specializing in: Mobile Web,
  Component Driven UIs, Universal JS (Isomorphic) Apps, ReactJS, NodeJS, Webpack
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: brianswisher
github_username:  brianswisher

# Build settings
markdown: kramdown
